### ISSUE TITLE
Write IANA Considerations Section

### ISSUE THREAD

**Issue by jiceatscion** [scionassociation/scion-cppki_I-D#26]
See [RFC 8126](https://www.rfc-editor.org/rfc/rfc8126.html)

(Copied from https://github.com/scionassociation/standards/issues/100)

**Comment by nicorusti** [comment]
@jiceatscion Wasn't this addressed in #25?

**Comment by jiceatscion** [comment]
Looks like it. There wasn't a link between the PR and the issue. Neither with the original issue:  https://github.com/scionassociation/standards/issues/100.

But if it's done, it's done.
