### ISSUE TITLE
Unaddressed Feedback from Reviews

### ISSUE THREAD

**Issue by jiceatscion** [scionassociation/scion-cppki_I-D#27]
(Moved from https://github.com/scionassociation/standards/issues/64)

IETF 115 Feedback Russ on specific sections: 

- [x] Section 2.2.1.4.1 is incomplete.  You do not say which string type is associated with the ISD-AS number attribute.  I suggest that you keep it simple and use PrintableString.
_--> This feedback is addressed in the new version of the draft, in the section Certificate Specification > Basic Fields._ 
- [x] Section 2.2.2.1.2 is confusing to me.  I do not understand the need for id-kp-root.  Further, the "MUST be set" language is not clear, since the extension is a list of OIDs.  The phrase "MUST be included" might be a better way to talk about it.
_--> This feedback is addressed in the new version of the draft._ 
- [ ] #28. 

General feedback Eliot:
- [x] Make sure the references are correct:
       - Normative references: Needed for the specification; specification is based on it.
       - Informative references: Provide background/additional information
- [x] Make sure MUST/MAY/SHOULD are used correctly (see also [RFC 8174](https://datatracker.ietf.org/doc/html/rfc8174)): 
       - MUST: Without this, the protocol will not work
       - SHOULD: Should do this unless you have a very good reason not to
       - MAY: Try to not use "MAY", unless not needed
- [ ] What text can be removed? Be concise. Make sure every word that is there must be there.

**Comment by nicorusti** [comment]
Resolving as remaining action items are in #28
