### ISSUE TITLE
General review - Remove forward references

### ISSUE THREAD

**Issue by nicorusti** [scionassociation/scion-cppki_I-D#36]
```  
The exact binaries that are required are described in a separate document.
```

Twin issues: 
- https://github.com/scionassociation/scion-cp_I-D/issues/58
- https://github.com/scionassociation/scion-dp_I-D/issues/45

TODO: 
- [x] @knmeynell update terminology and de-hyphenate as in https://github.com/scionassociation/scion-dp_I-D/pull/51
- [x] Add development note: https://github.com/scionassociation/scion-dp_I-D/issues/48
- [x] @nicorusti general re-read through the draft

**Comment by knmeynell** [comment]
After reviewing the text, I could only find one forward reference.
